"""
테스터 계정 12개 JWT 토큰 발급 + 문서 생성 스크립트

실행:
    cd API_Server
    python scripts/gen_tester_tokens.py

결과:
    API_Server/docs/TESTER_ACCOUNTS.md 자동 생성
    (기존 파일이 있으면 덮어씀)

요구사항:
    - .env 파일에 JWT_SECRET_KEY 설정 필요
    - API 서버 실행 불필요 (토큰을 로컬에서 직접 생성)
"""

import hashlib
import os
import sys
from pathlib import Path

# ── 경로 설정 ──────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
API_SERVER_DIR = SCRIPT_DIR.parent
ROOT_DIR = API_SERVER_DIR.parent
DOC_PATH = API_SERVER_DIR / "docs" / "TESTER_ACCOUNTS.md"

# .env 로드
from dotenv import load_dotenv
load_dotenv(ROOT_DIR / ".env")

JWT_SECRET = os.getenv("JWT_SECRET_KEY")
TOKEN_READY = bool(JWT_SECRET)

if TOKEN_READY:
    try:
        from jose import jwt
    except ImportError:
        sys.exit("[ERROR] python-jose 미설치: pip install python-jose")
else:
    print("[WARNING] JWT_SECRET_KEY 미설정 — 토큰 칸은 비워둡니다.")
    print("          .env에 JWT_SECRET_KEY 추가 후 재실행하면 토큰이 채워집니다.\n")

# ── 테스터 페르소나 ────────────────────────────────────────────────────────
TESTERS = [
    # (레이블, 군집, 연령, 특징)
    ("C0_저관여_50대", "C0", "50대", "저관여 일반 시청자 — 드라마·예능 가끔 시청"),
    ("C0_저관여_60대", "C0", "60대", "저관여 일반 시청자 — 뉴스·교양 중심"),
    ("C1_충성_50대",   "C1", "50대", "충성 시청자 — 주 4회 이상, 드라마·다큐 선호"),
    ("C1_충성_40대",   "C1", "40대", "충성 시청자 — 시청 이력 50건, 다양한 장르"),
    ("C1_충성_30대",   "C1", "30대", "충성 시청자 — OTT 병행, 트렌디 콘텐츠"),
    ("C1_충성_60대",   "C1", "60대", "충성 시청자 — 클래식·국악·다큐 선호"),
    ("C2_헤비_50대",   "C2", "50대", "헤비 유저 — 일 2시간 이상, SVOD 구독"),
    ("C2_헤비_40대",   "C2", "40대", "헤비 유저 — 주말 정주행, 시리즈 완주율 높음"),
    ("C2_헤비_30대",   "C2", "30대", "헤비 유저 — 장르 다양, 알림·찜 적극 활용"),
    ("C3_키즈_40대",   "C3", "40대", "키즈 보호자 — 어린이 콘텐츠 + 성인 드라마 병행"),
    ("C3_키즈_30대",   "C3", "30대", "키즈 보호자 — 애니메이션·교육 프로그램 위주"),
    ("C3_키즈_60대",   "C3", "60대", "키즈 보호자 — 손자녀 세대와 공동 시청"),
]

ALGORITHM = "HS256"
PLACEHOLDER = "⚠️ JWT_SECRET_KEY 설정 후 스크립트 재실행 필요"

# ── 토큰 생성 ──────────────────────────────────────────────────────────────
rows = []
for label, cluster, age, desc in TESTERS:
    uid = hashlib.sha256(("test_" + label).encode()).hexdigest()
    if TOKEN_READY:
        token = jwt.encode({"sub": uid}, JWT_SECRET, algorithm=ALGORITHM)
    else:
        token = PLACEHOLDER
    rows.append((label, cluster, age, desc, uid, token))

# ── 문서 작성 ──────────────────────────────────────────────────────────────
BASE_URL = "http://localhost:8000"   # 배포 환경으로 바꿔서 쓸 것

lines = [
    "# 테스터 계정 — JWT 토큰 발급 목록",
    "",
    "> **⚠️ 배포 환경 변경 시 이 파일을 재생성하세요.**  ",
    "> `API_Server/scripts/gen_tester_tokens.py` 를 다시 실행하면 최신 JWT로 덮어씁니다.",
    "> JWT는 만료 없음(셋톱박스 자동 로그인 정책). Secret이 바뀌면 모든 토큰 무효화.",
    "",
    f"**API Base URL**: `{BASE_URL}`  ",
    "**인증 방식**: `Authorization: Bearer <token>`",
    "",
    "---",
    "",
    "## 군집별 테스터 계정",
    "",
]

cluster_headers = {
    "C0": "### C0 — 저관여 (2명)",
    "C1": "### C1 — 충성 (4명)",
    "C2": "### C2 — 헤비 유저 (3명)",
    "C3": "### C3 — 키즈 보호자 (3명)",
}
current_cluster = None

for label, cluster, age, desc, uid, token in rows:
    if cluster != current_cluster:
        if current_cluster is not None:
            lines.append("")
        lines.append(cluster_headers[cluster])
        lines.append("")
        current_cluster = cluster

    lines += [
        f"#### {label}",
        f"> {desc}",
        "",
        f"| 항목 | 값 |",
        f"|------|----|",
        f"| **User ID** | `{uid}` |",
        f"| **JWT Token** | `{token}` |",
        "",
        "**curl 예시:**",
        "```bash",
        f'curl -H "Authorization: Bearer {token if TOKEN_READY else "<JWT_TOKEN>"}" \\',
        f"  {BASE_URL}/recommend/{uid}",
        "```",
        "",
    ]

# 전체 토큰 표 (빠른 복사용)
lines += [
    "---",
    "",
    "## 전체 토큰 요약표 (빠른 복사용)",
    "",
    "| 레이블 | User ID (앞 8자) | JWT Token |",
    "|--------|-----------------|-----------|",
]
for label, _, _, _, uid, token in rows:
    lines.append(f"| `{label}` | `{uid[:8]}...` | `{token}` |")

lines += [
    "",
    "---",
    "",
    "## 주요 테스트 엔드포인트",
    "",
    "| 목적 | 엔드포인트 | 인증 |",
    "|------|------------|------|",
    f"| 개인화 추천 | `GET /recommend/{{user_id}}` | 필요 |",
    f"| 홈 배너 | `GET /home/banner` | 선택 |",
    f"| 홈 섹션 | `GET /home/sections` | 불필요 |",
    f"| 개인화 섹션 | `GET /home/sections/{{user_id}}` | 필요 |",
    f"| VOD 검색 | `GET /vod/search?q={{query}}` | 불필요 |",
    f"| 시청 중 | `GET /user/me/watching` | 필요 |",
    f"| 시청 내역 | `GET /user/me/history` | 필요 |",
    f"| 찜 목록 | `GET /user/me/wishlist` | 필요 |",
    f"| 유사 콘텐츠 | `GET /similar/{{asset_id}}` | 불필요 |",
    f"| 포인트 | `GET /user/me/points` | 필요 |",
    "",
    "---",
    "",
    f"*generated by `scripts/gen_tester_tokens.py`*",
]

DOC_PATH.write_text("\n".join(lines), encoding="utf-8")
print(f"[OK] 문서 생성 완료: {DOC_PATH}")
print(f"     테스터 {len(rows)}명 / JWT {len(rows)}개")
