description: AI Hub 음식 데이터셋 71클래스 → 한국어 카테고리 매핑
names:
  0: 빵류
  1: 샌드위치/토스트
  2: 면류(쌀국수/우동)
  3: 치킨
  4: 피자
  5: 덮밥/포케
  6: 케이크/머핀
  7: 파스타
  8: 김밥/초밥
  9: 꼬치/스테이크
  10: 볶음류
  11: 떡
  12: 매운탕/탕류
  13: 크로와상/타르트
  14: 돈가스/튀김
  15: 식빵/와플
  16: 샐러드
  17: 만두
  18: 전골/찌개
  19: 국수/칼국수
  20: 새우튀김/어묵
  21: 전통빵/호빵
  22: 라멘/라면
  23: 떡볶이
  24: 크림빵/롤
  25: 짬뽕/짜장
  26: 시리얼/파이
  27: 회/생선회
  28: 찌개/순두부
  29: 족발/순대
  30: 커피
  31: 생선구이
  32: 커리/수프
  33: 그라탕/리조또
  34: 해물볶음
  35: 죽/수프
  36: 곰탕/해장국
  37: 찜류
  38: 밀크티/라떼
  39: 튀김간식
  40: 닭발/동파육
  41: 죽/디저트
  42: 도넛/꽈배기
  43: 비빔밥
  44: 버거
  45: 국밥/떡국
  46: 두부요리
  47: 나베/전골
  48: 과일주스
  49: 전/부침개
  50: 에이드
  51: 잎차류
  52: 중식볶음
  53: 볶음밥
  54: 미역국/기타탕
  55: 스무디
  56: 옥수수/약밥
  57: 소떡소떡
  58: 추어전
  59: 어니언링/튀김
  60: 나쵸
  61: 전통음료
  62: 묵밥
  63: 오믈렛
  64: 김치찜
  65: 빙수
  66: 은행구이
  67: 생선조림
  68: 메밀전
  69: 꼬막무침
  70: 기타
names_list:
- 빵류
- 샌드위치/토스트
- 면류(쌀국수/우동)
- 치킨
- 피자
- 덮밥/포케
- 케이크/머핀
- 파스타
- 김밥/초밥
- 꼬치/스테이크
- 볶음류
- 떡
- 매운탕/탕류
- 크로와상/타르트
- 돈가스/튀김
- 식빵/와플
- 샐러드
- 만두
- 전골/찌개
- 국수/칼국수
- 새우튀김/어묵
- 전통빵/호빵
- 라멘/라면
- 떡볶이
- 크림빵/롤
- 짬뽕/짜장
- 시리얼/파이
- 회/생선회
- 찌개/순두부
- 족발/순대
- 커피
- 생선구이
- 커리/수프
- 그라탕/리조또
- 해물볶음
- 죽/수프
- 곰탕/해장국
- 찜류
- 밀크티/라떼
- 튀김간식
- 닭발/동파육
- 죽/디저트
- 도넛/꽈배기
- 비빔밥
- 버거
- 국밥/떡국
- 두부요리
- 나베/전골
- 과일주스
- 전/부침개
- 에이드
- 잎차류
- 중식볶음
- 볶음밥
- 미역국/기타탕
- 스무디
- 옥수수/약밥
- 소떡소떡
- 추어전
- 어니언링/튀김
- 나쵸
- 전통음료
- 묵밥
- 오믈렛
- 김치찜
- 빙수
- 은행구이
- 생선조림
- 메밀전
- 꼬막무침
- 기타
