description: AI Hub 음식 데이터셋 761종 메뉴명 매핑 (v2, 메뉴 단위)
names:
  0: 맥앤치즈
  1: 김치나베
  2: 해천탕
  3: 추어전
  4: 추어만두
  5: 봉골레파스타
  6: 난자완스
  7: 황태전골
  8: 물회
  9: 빠네로제파스타
  10: 메밀소바
  11: 로스카츠(등심)
  12: 동파육
  13: 차슈바오
  14: 까르보네피자
  15: 고르곤졸라피자
  16: 황태육개장
  17: 추어전골
  18: 어탕국수
  19: 내장볶음
  20: 마라쌀국수
  21: 돈코츠라멘
  22: 오피자
  23: 꿍 팟 퐁 커리
  24: 감자그라탕
  25: 추어칼국수
  26: 얼큰황태우거지탕
  27: 반계탕
  28: 물갈비
  29: 새우크림파스타
  30: 미소라멘
  31: 멘보샤
  32: 마라빤
  33: 로제리조또
  34: 라조기
  35: 돌체피자
  36: 닭고기쌀국수
  37: 나시고랭볶음밥
  38: 나가사끼짬뽕
  39: 소갈비살꼬지
  40: 불고기피자(씬)
  41: 탄탄멘
  42: 카야토스트
  43: 야끼만두
  44: 초코머핀
  45: 젤리롤케잌
  46: 나폴리피자
  47: 꿔바로우
  48: 까르보나라파스타
  49: 규동
  50: 오징어회
  51: 아바이순대
  52: 술국
  53: 낙지호롱
  54: 새우토마토스파게티
  55: 삼겹살스테이크
  56: 분짜
  57: 부타동
  58: 볼로네제토마토파스타
  59: 베이컨크림파스타
  60: 마라살꼬치
  61: 똠얌꿍
  62: 돈부리덮밥
  63: 냉라멘
  64: 나쵸
  65: 치킨포케
  66: 치킨부리또
  67: 짜조
  68: 중화볶음면
  69: 오일파스타
  70: 샤오롱바오
  71: 파닭
  72: 양념반후라이드반치킨(뼈)
  73: 불백(뚝배기불고기)
  74: 단호박샐러드
  75: 치즈닭갈비
  76: 러스크
  77: 오트밀시리얼
  78: 블루베리시리얼
  79: 크림치즈베이글
  80: 크림도넛
  81: 고구마그라탕
  82: 건두부볶음
  83: 갈릭난
  84: 황태찜
  85: 황태부대찌개
  86: 황태닭곰탕
  87: 황태닭개장
  88: 알내장탕
  89: 북어찜
  90: 멍게(활)
  91: 막회
  92: 대하찜
  93: 대하구이
  94: 광어회
  95: 비스마르크피자
  96: 버섯리조또
  97: 바질크림파스타
  98: 매운해물쌀국수
  99: 로제파스타
  100: 카레우동
  101: 치킨타코
  102: 차슈동
  103: 연어포케
  104: 알리오올리오파스타
  105: 닭윙양념치킨
  106: 닭가슴살샌드위치
  107: 김치참치컵밥
  108: 간장치킨(뼈)
  109: 푸팟퐁커리
  110: 팟타이
  111: 토르티야
  112: 참치마요덮밥
  113: 순살양념반후라이드반치킨
  114: 순대전골
  115: 소고기초밥
  116: 멸치국수
  117: 쑥버무리
  118: 슈크림크로와상
  119: 버터크림빵
  120: 녹차마카롱
  121: 초코크로와상
  122: 초코롤케잌
  123: 초계탕
  124: 밀푀유나베
  125: 풍기크림파스타
  126: 만두전골
  127: 꽃빵
  128: 깐쇼새우
  129: 황태떡국
  130: 황태국밥
  131: 해신탕
  132: 초계국수
  133: 나주곰탕
  134: 사천볶음쌀국수
  135: 불고기쌀국수
  136: 볶음쌀국수
  137: 마르게리따피자
  138: 마라쇼룽샤
  139: 마라샹궈
  140: 또띠아피자
  141: 날치알크림파스타
  142: 치킨커리
  143: 차슈라멘
  144: 오코노미야끼
  145: 에비(텐)동
  146: 어니언베이컨피자
  147: 양꼬치
  148: 쏨땀
  149: 소힘줄(스지) 쌀국수
  150: 소고기퀘사디아
  151: 부대떡볶이
  152: 바질샌드위치
  153: 딸기샌드위치
  154: 까르보나라떡볶이
  155: 해산물팟타이
  156: 해물누룽지탕
  157: 간장달걀밥
  158: 훈제양념치킨
  159: 치즈피자
  160: 옛날통닭
  161: 아보카도샌드위치
  162: 순살양념반간장반치킨
  163: 새우볼
  164: 삼치구이
  165: 묵밥(묵사발)
  166: 모둠순대
  167: 먹태
  168: 마약옥수수
  169: 떡만두라면
  170: 돼지두루치기
  171: 닭발볶음
  172: 닭가슴살샐러드
  173: 호박송편
  174: 앙금절편
  175: 빙떡
  176: 감자떡
  177: 해물라면
  178: 칼국수
  179: 참소라초밥
  180: 은행구이
  181: 육회초밥
  182: 우럭매운탕
  183: 옥수수빵
  184: 아이스크림와플
  185: 시나몬크로플
  186: 소금빵
  187: 밤식빵
  188: 바닐라아이스크림와플
  189: 딸기타르트
  190: 딸기크로플
  191: 녹차머핀
  192: 까눌레
  193: 고구마핫도그
  194: 경주찰보리빵
  195: 후르츠링시리얼
  196: 양념닭가슴살
  197: 플레인베이글
  198: 치아바타
  199: 초코크레이프
  200: 초코와플
  201: 황태국
  202: 새우(쉬림프)부리또
  203: 튀김꽃빵
  204: 닭가슴살스테이크
  205: 노가리
  206: 햄에그샌드위치
  207: 우럭초밥
  208: 꽈배기
  209: 참치죽
  210: 가라아케
  211: 황태콩나물해장국
  212: 장어탕
  213: 대구탕
  214: 대구뽈찜
  215: 가자미구이
  216: 베트남식 볶음면
  217: 명란크림파스타
  218: 마살라커리
  219: 마라롱샤
  220: 짬뽕차돌쌀국수
  221: 중화냉면
  222: 유린기
  223: 우삼겹커리
  224: 양지쌀국수
  225: 양장피
  226: 양갈비살꼬치
  227: 소대창쌀국수
  228: 소고기타코
  229: 불고기버거
  230: 베이컨토스트
  231: 베이컨샌드위치
  232: 마요치킨(뼈)
  233: 땅콩샌드위치
  234: 닭윙간장치킨
  235: 닭윙&닭다리양념치킨
  236: 닭윙&닭다리간장치킨
  237: 꼬막짬뽕
  238: 고구마피자(씬)
  239: 감자토스트
  240: BLT샌드위치
  241: 해물리조또
  242: 피쉬볼
  243: 탄두리치킨
  244: 피자토스트
  245: 프렌치토스트
  246: 크림떡볶이
  247: 콤비네이션피자(팬)
  248: 카레컵밥
  249: 치킨토스트
  250: 충무김밥
  251: 제육컵밥
  252: 자장떡볶이
  253: 우삼겹떡볶이
  254: 에그샌드위치
  255: 순살크림(크리미)치킨
  256: 순살어니언치킨
  257: 순살마늘치킨
  258: 순살깐풍치킨
  259: 비빔막국수
  260: 버팔로윙
  261: 버섯피자
  262: 바지락된장찌개
  263: 닭내장볶음
  264: 닭계장
  265: 날치알주먹밥
  266: 고구마치즈돈가스
  267: 고구마샐러드
  268: 게살볶음밥
  269: 쑥떡
  270: 소떡소떡
  271: 모시송편
  272: 고구마떡
  273: 황도
  274: 해물순두부찌개
  275: 해물뚝배기
  276: 함박스테이크
  277: 콘샐러드
  278: 칠리새우
  279: 치즈곱창
  280: 제육볶음
  281: 잡채말이튀김
  282: 연어샐러드
  283: 얼큰칼국수
  284: 양평해장국
  285: 순두부짬뽕
  286: 연유빵
  287: 애플크럼블
  288: 앙버터호두과자
  289: 앙버터치아바타
  290: 아몬드크로와상
  291: 브라우니
  292: 불고기파니니
  293: 바닐라마카롱
  294: 바나나와플
  295: 마늘빵
  296: 딸기크레이프
  297: 딸기마카롱
  298: 당근케이크
  299: 녹차롤케잌
  300: 초코시리얼
  301: 닭가슴살소시지
  302: 김치죽
  303: 후레쉬빵
  304: 황치즈마카롱
  305: 호두빵
  306: 피자빵
  307: 파네토네
  308: 퀸아망
  309: 쿠키슈
  310: 치즈번
  311: 찹쌀도너츠
  312: 인절미크로플
  313: 추어튀김
  314: 황태미역국
  315: 시오라멘
  316: 새우로제파스타
  317: 버터난
  318: 닭다리양념치킨
  319: 햄치즈파니니
  320: 옥수수식빵
  321: 감바스
  322: 가지만두
  323: 소라숙회
  324: 낙지탕탕이
  325: 새우샤오롱바오
  326: 사천탕수육
  327: 마라탕
  328: 치킨퀘사디아
  329: 춘권
  330: 짬뽕 쌀국수
  331: 우육면
  332: 우삼겹팟타이
  333: 에비카츠
  334: 아라비아따파스타
  335: 불고기컵밥
  336: 베이컨포테이토피자
  337: 베이컨치즈버거
  338: 반미샌드위치
  339: 떡강정
  340: 돈가스김밥
  341: 닭윙후라이드치킨
  342: 김치참치마요컵밥
  343: 히레카츠(안심)
  344: 훈제연어덮밥
  345: 하와이안피자
  346: 팔보채
  347: 토마토계란볶음
  348: 타코와사비
  349: 카츠동
  350: 카츠나베
  351: 훈제치킨(뼈)
  352: 햄치즈토스트
  353: 햄샌드위치
  354: 페퍼로니피자(씬)
  355: 클럽샌드위치
  356: 크리스피치킨(뼈)
  357: 치즈샌드위치
  358: 치즈라볶이
  359: 참치마요컵밥
  360: 에그마요샌드위치
  361: 어니언치킨(뼈)
  362: 양념반간장반치킨(뼈)
  363: 순살후라이드치킨
  364: 순살간장파닭
  365: 새우피자(씬)
  366: 새우토스트
  367: 새우샌드위치
  368: 새우김밥
  369: 빨간참치김밥
  370: 새우만두
  371: 빈대떡
  372: 비프샐러드
  373: 민물새우튀김
  374: 리코타치즈샐러드
  375: 두부샐러드
  376: 두부버섯전골
  377: 두부두루치기
  378: 돼지짜글이
  379: 달걀초밥
  380: 굴비구이
  381: 굴국밥
  382: 국물닭발
  383: 검은콩국수
  384: 호떡
  385: 오메기떡
  386: 영양떡
  387: 크림함박스테이크
  388: 크림우동
  389: 코다리냉면
  390: 케이준샐러드
  391: 치즈달걀말이
  392: 차돌된장찌개
  393: 주꾸미삽겹살볶음
  394: 조기구이
  395: 전복버터구이
  396: 쟁반국수
  397: 장어롤
  398: 울면
  399: 연어롤
  400: 어니언링
  401: 시래기해장국
  402: 연유크림빵
  403: 앙버터크로와상
  404: 시나몬롤
  405: 생크림케이크
  406: 밀크크레이프
  407: 명란바게트
  408: 메론빵
  409: 레인보우케이크
  410: 딸기크로와상
  411: 단호박크럼블
  412: 치즈볼
  413: 고구마케이크
  414: 고구마식빵
  415: 감자핫도그
  416: 닭가슴살
  417: 녹두죽
  418: 낙지죽
  419: 호두타르트
  420: 크로크무슈
  421: 야채호빵
  422: 치즈케이크
  423: 초코크로플
  424: 팥붕어빵
  425: 초코아이스크림와플
  426: 초코스콘
  427: 초코소라빵
  428: 초코까눌레
  429: 찹쌀꽈배기
  430: 우유크림빵
  431: 우유마카롱
  432: 훈제닭가슴살소시지
  433: 루꼴라피자
  434: 빠네크림파스타
  435: 닭다리후라이드치킨
  436: 닭다리간장치킨
  437: 플레인난
  438: 토마토리조또
  439: 전주비빔컵밥
  440: 투움바떡볶이
  441: 새우장초밥
  442: 단팥호빵
  443: 야채고로케
  444: 찹스테이크
  445: 아몬드시리얼
  446: 옥수수시리얼
  447: 카페라떼(HOT)
  448: 히비스커스
  449: 민트초코라떼
  450: 유자스무디
  451: 가이 팟 퐁 커리
  452: 황태만두국
  453: 개불
  454: 새우오일파스타
  455: 치킨파히타
  456: 차돌양지쌀국수
  457: 유산슬
  458: 시카고피자
  459: 소유라멘
  460: 소고기부리또
  461: 멸치김밥
  462: 로제돈가스
  463: 땡초멸치김밥
  464: 땡초김밥
  465: 곱창떡볶이
  466: 계란토스트
  467: 갈비치킨
  468: 간장반후라이드반치킨(뼈)
  469: 해물쌀국수
  470: 풍기피자
  471: 타코야끼
  472: 크림새우
  473: 카이센동
  474: 페퍼로니피자(팬)
  475: 콤비네이션피자(씬)
  476: 치킨버거
  477: 치킨마요덮밥
  478: 참치샌드위치
  479: 차돌떡볶이
  480: 스팸김치컵밥
  481: 순살마요치킨
  482: 순살로제치킨
  483: 새우피자(팬)
  484: 불닭마요컵밥
  485: 빨계떡
  486: 비빔밀면
  487: 버섯샐러드
  488: 바지락칼국수
  489: 무뼈닭발
  490: 로제찜닭
  491: 떡만둣국
  492: 돼지간
  493: 돌솥비빔밥
  494: 닭모래집볶음
  495: 단호박피자
  496: 김치찜
  497: 고추장불고기
  498: 고기국수
  499: 고구마돈가스
  500: 감자수제비
  501: 갈비전골
  502: 감자빵
  503: 감자고로케
  504: 콩떡
  505: 약밥
  506: 무지개떡
  507: 코울슬로
  508: 케이준양념감자
  509: 진주냉면
  510: 오징어순대
  511: 어묵튀김
  512: 야채곱창볶음
  513: 오트밀식빵
  514: 에그타르트
  515: 애플파이
  516: 아이스크림크로플
  517: 소시지빵
  518: 소시지고로케
  519: 생크림크로플
  520: 생크림와플
  521: 생크림식빵
  522: 피자호빵
  523: 바닐라머핀
  524: 민트초코마카롱
  525: 모카번
  526: 머랭쿠키
  527: 마들렌
  528: 단팥크림빵
  529: 깨찰빵
  530: 쿠키엔크림케이크
  531: 계란빵
  532: 경주빵
  533: 게살고로케
  534: 핫바(어묵소시지)
  535: 그래놀라시리얼
  536: 오레오시리얼
  537: 크림수프
  538: 콘수프
  539: 흑임자죽
  540: 김치낙지죽
  541: 휘낭시에
  542: 햄치즈베이글
  543: 플레인크로플
  544: 통밀식빵
  545: 크림치즈호두빵
  546: 치즈크로플
  547: 초코파운드
  548: 초코마카롱
  549: 잡채고로케
  550: 꼬마김밥
  551: 깐풍치킨(뼈)
  552: 치즈버거
  553: 차돌짬뽕
  554: 쟁반짬뽕
  555: 순살양념파닭
  556: 미니족발
  557: 로제치킨(뼈)
  558: 들깨수제비
  559: 냉우동
  560: 꽁치김치찌개
  561: 감자옹심이
  562: 가리비초밥
  563: 후라이드치킨(뼈)
  564: 망개떡
  565: 치킨샐러드
  566: 올갱이해장국
  567: 오돌뼈볶음
  568: 새우튀김우동
  569: 슈크림빵
  570: 바게트빵
  571: 모짜렐라핫도그
  572: 맘모스빵
  573: 마늘바게트
  574: 딸기롤케잌
  575: 글레이즈드도넛
  576: 술떡
  577: 카레고로케
  578: 초코베이글
  579: 우유식빵
  580: 소시지(프랑크)
  581: 쇠고기죽
  582: 장어튀김
  583: 아이스카페라떼
  584: 고구마라떼
  585: 카라멜마끼아또(HOT)
  586: 흑당밀크티
  587: 밀크쉐이크
  588: 미숫가루
  589: 말차라떼
  590: 키위주스
  591: 체리콕에이드
  592: 망고주스
  593: 망고에이드
  594: 아샷추
  595: 아이스티라미수라떼
  596: 아이스카푸치노
  597: 아이스모카라떼
  598: 아이스돌체라떼
  599: 돌체라떼(HOT)
  600: 플레인요거트스무디
  601: 오곡라떼
  602: 그린밀크티
  603: 블루베리스무디
  604: 레몬차
  605: 딸기에이드
  606: 딸기바나나주스
  607: 아이스헤이즐넛라떼
  608: 똠얌꿍쌀국수
  609: 마라떡볶이
  610: 마늘치킨(뼈)
  611: 닭갈비컵밥
  612: 김치알컵밥
  613: 크림(크리미)치킨(뼈)
  614: 쟁반짜장
  615: 순살파닭
  616: 순살간장반후라이드반치킨
  617: 새우버거
  618: 소고기타다끼초밥
  619: 소고기간
  620: 석갈비
  621: 생태찌개
  622: 물밀면
  623: 묵은지감자탕
  624: 메밀만두
  625: 메밀전
  626: 등갈비찜
  627: 납작만두
  628: 낙지덮밥
  629: 광어매운탕
  630: 갈치구이
  631: 간장닭갈비
  632: 옥수수떡
  633: 피자돈까스
  634: 캘리포니아롤
  635: 완두앙금빵
  636: 얼그레이마카롱
  637: 블루베리마카롱
  638: 말차까눌레
  639: 딸기케이크
  640: 깜빠뉴
  641: 훈제닭가슴살
  642: 쇠고기수프
  643: 브로콜리수프
  644: 핫도그
  645: 플레인스콘
  646: 티라미수
  647: 크로칸슈
  648: 카스테라
  649: 초코케이크
  650: 냉채족발
  651: 고구마피자(팬)
  652: 치즈떡볶이
  653: 유부우동
  654: 유니짜장
  655: 스팸김밥
  656: 순살훈제양념치킨
  657: 순살간장치킨
  658: 묵은지갈비찜
  659: 명태조림
  660: 도리뱅뱅이
  661: 달걀오믈렛
  662: 꽁치구이
  663: 꼬막비빔밥
  664: 꼬막무침
  665: 김피탕
  666: 곱도리탕
  667: 곱창쭈꾸미
  668: 고등어구이
  669: 감자만두
  670: 모시떡
  671: 편육
  672: 팥칼국수
  673: 크레미롤
  674: 콩나물불고기(콩불)
  675: 칠리새우덮밥
  676: 천엽
  677: 찰순대
  678: 삼선간짜장
  679: 소세지크로와상
  680: 소보루빵
  681: 새우고로케
  682: 블루베리파이
  683: 단팥빵
  684: 호두과자
  685: 튀김소보루
  686: 카라멜마카롱
  687: 슈크림붕어빵
  688: 산낙지회
  689: 멍게비빔밥
  690: 양송이수프
  691: 삼계전복죽
  692: 헤이즐넛라떼(HOT)
  693: 토피넛라떼
  694: 아이스토피넛라떼
  695: 아이스초코모카라떼
  696: 아메리카노(HOT)
  697: 시나몬라떼(HOT)
  698: 더치커피
  699: 카모마일차
  700: 얼그레이
  701: 루이보스차
  702: 팥빙수
  703: 초코밀크티
  704: 죠리퐁라떼
  705: 연유라떼
  706: 아이스초코
  707: 녹차라떼
  708: 청귤에이드
  709: 자몽차
  710: 수박주스
  711: 복숭아아이스티
  712: 레몬에이드
  713: 레몬아이스티
  714: 티라미수라떼(HOT)
  715: 바닐라라떼
  716: 헤이즐넛아메리카노(HOT)
  717: 카푸치노(HOT)
  718: 초코모카라떼(HOT)
  719: 아이스카라멜마끼아또
  720: 홍차
  721: 호박식혜
  722: 핫초코
  723: 초코쉐이크
  724: 인절미빙수
  725: 바나나쉐이크
  726: 토마토주스
  727: 키위스무디
  728: 청귤차
  729: 유자차
  730: 망고스무디
  731: 딸기빙수
  732: 콜드브루
  733: 코코넛라떼(HOT)
  734: 아이스초코라떼
  735: 아이스아메리카노
  736: 흑당라떼
  737: 달고나라떼
  738: 오렌지에이드
  739: 블루레몬에이드
  740: 모히또
  741: 소곱창쌀국수
  742: 콜드브루라떼
  743: 아이스코코넛라떼
  744: 녹차
  745: 얼그레이밀크티
  746: 청포도에이드
  747: 자몽에이드
  748: 사과주스
  749: 딸기주스
  750: 딸기스무디
  751: 깔라만시에이드
  752: 에스프레소
  753: 아이스시나몬라떼
  754: 모카라떼(HOT)
  755: 식혜
  756: 쿠키쉐이크
  757: 초코스무디
  758: 초코라떼(HOT)
  759: 자몽주스
  760: 바나나주스
